[package]
name = "metal-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cocoa = "0.25.0"
core-graphics-types = "0.1.3"
metal = "0.27.0"
winit = "0.28"
